### PR TITLE
Add man page and update the Makefile

### PR DESCRIPTION
**Pull request by JR1994**
I am pretty new to git. I made some changes and placed pull requests to the upstream repo. Since I am cloning yours I thought you would want to take a look at them as well. I have made a man page for mbpfan and updated the Makefile. The Makefile will use the install command instad of cp. It will also install the systemd .service file, the man page, and the README file. These changes will also make packaging easier.

### CODE REVIEW

**Comment by dgraziotin** [comment]
Thank you very much for this. It will take a while before I can review this PR. Please have some patience.

**Comment by JR1994** [comment]
No worries this app has been a great for my MacBook Pro running Debian.

**Comment by JR1994** [comment]
Any update on this request?

**Comment by dgraziotin** [comment]
I'll likely look at it during the last days of August. Sorry, big deadlines at work!

Daniel Graziotin
@dgraziotin
ineed.coffee

**Comment by dgraziotin** [comment]
@JR1994 I have finally started looking at your PR. I am not a Makefile expert (at all), and was wondering what would be the consequences of [a Makefile that incorporates systemd](https://github.com/dgraziotin/mbpfan/pull/80/commits/8e68a2b87b450ae8b1581be0b14ae21b9ebac772#diff-b67911656ef5d18c4ae36cb6741b7965R79) for systems that do not use systemd. Do you have any clue?

**Comment by JR1994** [comment]
It will only install the systemd.service file and attempt to launch it. One
will still need to run systemctl enable mbpfan.service and systemctl start
mbpfan.service

**Comment by dgraziotin** [comment]
That's right. What about those distros that do not use systemd?

Daniel Graziotin
@dgraziotin
ineed.coffee

**Comment by JR1994** [comment]
There are fewer and fewer that are non-systemd. Gentoo still uses OpenRC, but you can also use systemd. Anything Debian based after Jessie is on systemd. Linux Mint 18 is now on sustemd. Ubuntu has been on systemd since 15.04. More and more systemd is becoming the standard.

**Comment by dgraziotin** [comment]
Sure, but there are still distros not using it, e.g., Slackware (on which I developed mbpfan initially) and older versions of Ubuntu, Debian, Fedora, etc.. Mbpfan aims to be distro independent. 

Now, I am wondering what would happen when one does a `make install` on a system where systemd is not present. Would it fail? Would it just print an error message? 

Shall we instead go for a `make systemdinstall` instead?

**Comment by JR1994** [comment]
On 08/30, Daniel Graziotin wrote:
> Sure, but there are still distros not using it, e.g., Slackware (on which I developed mbpfan initially) and older versions of Ubuntu, Debian, Fedora, etc.. Mbpfan aims to be distro independent. 
> 
> Now, I am wondering what would happen when one does a `make install` on a system where systemd is not present. Would it fail? Would it just print an error message? 
> 
I think it will just create the /lib/systemd directory and that is all. However I am thinking that we may not need that line. In Debian they use dh_auto and dh_install to overide the upstream Makefile. I think gentoo ebuilds and Arch PKGBUILDs do the same. So the downstream distro maintainers can decide how to install that portion. Your thoughts?

Thanks
Herminio

**Comment by dgraziotin** [comment]
That would definitely solve the doubts. I was also wondering if it was a job for packages to install distro-dependent files. If that sounds OK to you, I will merge your parts without the systemd related code.

**Comment by JR1994** [comment]
I am not 100% sure but think so.

**Comment by dgraziotin** [comment]
Ok, I created a [branch](https://github.com/dgraziotin/mbpfan/tree/JR1994-master) with your edits and some small modifications (one of which is deleting the -Wall option from the Makefile, as this is a separate issue to be addressed). Does it look OK to you? Feel free to add yourself to the AUTHORS file!

**Comment by JR1994** [comment]
Looks good. Thanks for the offer!

Herminio

On Wed, Aug 31, 2016 at 12:47 AM, Daniel Graziotin <notifications@github.com

**Comment by dgraziotin** [comment]
@JR1994 thanks again for this!

**Comment by JR1994** [comment]
You are welcome

**Pull request merged**
