### PR TITLE
return to function

### PR DESCRIPTION
**Pull request by rmusial**
I had submitted some changes before to make mbpfan work with Clang but they were not in line with your request for K&R C standards. This time I added return 0; to function at line 106 in minunit.c to prevent core dump when compiled with Clang. Without it when you run sudo make tests with clang you get this...

Starting the tests..
It is normal for them to take a bit to finish.
Detected kernel version: 4
Detected kernel minor revision: 8
Detected kernel version: 4
Detected kernel minor revision: 8
Using new sensor path for kernel >= 3.0.15
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp
Found 3 sensors
Found 1 fans
Detected kernel version: 4
Detected kernel minor revision: 8
Using new sensor path for kernel >= 3.0.15
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp
Found 3 sensors
Makefile:60: recipe for target 'tests' failed
make: *** [tests] Illegal instruction (core dumped)

### CODE REVIEW

**Comment by dgraziotin** [comment]
Sorry for the delay. Thank you for the PR. I am not enough familiar with clang. Could you please post here the steps for reproducing the issues (that is, how you compile mbpfan)?

**Comment by rmusial** [comment]
No problem!



Since Clang/Clang++ is intended to be a drop in replacement,  all I do
is edit the Makefile, where it uses G++ I replace that with clang++


then I follow the standard steps in the README of make, sudo make
install, sudo make tests.




On Wed, Dec 14, 2016, at 03:08 AM, Daniel Graziotin wrote:

> Sorry for the delay. Thank you for the PR. I am not enough familiar
> with clang. Could you please post here the steps for reproducing the
> issues (that is, how you compile mbpfan)?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/dgraziotin/mbpfan/pull/91#issuecomment-266969575

**Comment by rmusial** [comment]
Also, it may be worth noting that mbpfan compiles fine, tests fine, and
runs fine with no modification running GCC on my system. mbpfan compiles
fine, tests fine, and runs fine with the PR I submitted with Clang. I've
replicated these findings on Ubuntu 16.04 and 16.10, Fedora 23, 24.

**Comment by dgraziotin** [comment]
Thank you!

**Pull request merged**
